# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java Project met Maven

on:
  push:
    branches: master

jobs:
  maven_Testing_Building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Builden met Maven
        run: mvn -B package --file pom.xml